export const categoryList = [
  { name: 'American', value: 'american' },
  { name: 'Barbeque', value: 'bbq' },
  { name: 'Brazilian', value: 'brazilian' },
  { name: 'Breakfast&Brunch', value: 'breakfast_brunch' },
  { name: 'Burgers', value: 'burgers' },
  { name: 'Cafes', value: 'cafes' },
  { name: 'Cajun/Creole', value: 'cajun' },
  { name: 'Chinese', value: 'chinese' },
  { name: 'Cuban', value: 'cuban' },
  { name: 'Delis', value: 'delis' },
  { name: 'Diners', value: 'diners' },
  { name: 'Fast Food', value: 'hotdogs' },
  { name: 'Filipino', value: 'filipino' },
  { name: 'Gastropubs', value: 'gastropubs' },
  { name: 'German', value: 'german' },
  { name: 'Gluten-Free', value: 'gluten_free' },
  { name: 'Greek', value: 'greek' },
  { name: 'Indian', value: 'indpak' },
  { name: 'Italian', value: 'italian' },
  { name: 'Japanese', value: 'japanese' },
  { name: 'Korean', value: 'korean' },
  { name: 'Latin-American', value: 'latin' },
  { name: 'Mediterranean', value: 'mediterranean' },
  { name: 'Mexican', value: 'mexican' },
  { name: 'Noodles', value: 'noodles' },
  { name: 'Pizza', value: 'pizza' },
  { name: 'Portuguese', value: 'portuguese' },
  { name: 'Puerto-Rican', value: 'puertorican' },
  { name: 'Salad', value: 'salad' },
  { name: 'Sandwiches', value: 'sandwiches' },
  { name: 'Seafood', value: 'seafood' },
  { name: 'Soul Food', value: 'soulfood' },
  { name: 'Southern', value: 'southern' },
  { name: 'Spanish', value: 'spanish' },
  { name: 'Steakhouses', value: 'steak' },
  { name: 'Sushi', value: 'sushi' },
  { name: 'Taiwanese', value: 'taiwanese' },
  { name: 'Tapas', value: 'tapas' },
  { name: 'Tex-Mex', value: 'tex-mex' },
  { name: 'Thai', value: 'thai' },
  { name: 'Vegan', value: 'vegan' },
  { name: 'Vegetarian', value: 'vegetarian' },
  { name: 'Vietnamese', value: 'vietnamese' }
]